# Generated by Django 4.2.2 on 2023-06-19 15:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SonsTimes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField()),
                ('price', models.DecimalField(decimal_places=0, help_text='قیمت را به <strong>تومان</strong> وارد کنید.', max_digits=10)),
                ('holiday_price', models.DecimalField(decimal_places=0, help_text='قیمت را به <strong>تومان</strong> وارد کنید.', max_digits=10)),
            ],
            options={
                'verbose_name': 'Sons Time',
                'verbose_name_plural': 'Sons Times',
                'db_table': 'ReserveSystem_sons_times',
                'ordering': ['time'],
            },
        ),
        migrations.CreateModel(
            name='Reservations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('price', models.DecimalField(decimal_places=0, max_digits=10)),
                ('is_paid', models.BooleanField(default=False)),
                ('authority', models.BigIntegerField(blank=True, null=True)),
                ('RefID', models.BigIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sons_time', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sons_time_reserves', to='reservations.sonstimes')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_reserves', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ReserveSystem_reservations',
            },
        ),
    ]
