# Generated by Django 4.2.2 on 2023-06-15 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Reservations',
        ),
    ]
