# Generated by Django 4.2.2 on 2023-06-20 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservations',
            name='count',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
