# Generated by Django 4.2.2 on 2023-06-19 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0002_alter_reservations_finally_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservations',
            name='RfID',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='reservations',
            name='authority',
            field=models.BigIntegerField(),
        ),
    ]
