# Generated by Django 4.2.2 on 2023-06-19 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0003_alter_reservations_rfid_alter_reservations_authority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservations',
            name='RfID',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='reservations',
            name='authority',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
