# Generated by Django 4.2.2 on 2023-06-16 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0003_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sonstimes',
            options={'ordering': ['time']},
        ),
        migrations.AlterModelTable(
            name='sonstimes',
            table='ReserveSystem_sons_times',
        ),
    ]
