# Generated by Django 4.2.2 on 2023-06-18 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0005_alter_sonstimes_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservations',
            name='sons_time',
        ),
        migrations.AddField(
            model_name='reservations',
            name='time',
            field=models.TimeField(default='09:00'),
        ),
    ]
