# Generated by Django 4.2.2 on 2023-06-18 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0006_remove_reservations_sons_time_reservations_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservations',
            name='time',
            field=models.TimeField(),
        ),
    ]
