# Generated by Django 4.2.2 on 2023-06-16 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_user_avatar_remove_user_email_active_code'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='user',
            table='ReserveSystem_accounts',
        ),
    ]
